### ISSUE TITLE
Redirect when users try to load revisions in the Block Editor that have already been published.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/revisions-extended#10]
The front end already does this, but because the front end is loaded with lower priority, there's an awkward delay. Serverside is probably the best approach.

If the revision is not in the `future` or `pending` state, redirect to somewhere appropriate.

**Comment by coreymckrill** [comment]
#35 doesn't redirect, but it does show an error message instead of loading the block editor. I think this is sufficient, as there shouldn't be any links in the UI anywhere that would take someone to the editor for an already-published revision, so you'd have to type the URL in manually.
