### ISSUE TITLE
Editor scrollbar overlays button dropdown in Firefox

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/revisions-extended#105]
This may be another browser-specific issue that should be reported upstream, but I can't find any examples of this in normal Gutenberg, so I'm not sure. I can't reproduce this in Chrome, so I think it's just Firefox.

![](https://d.pr/i/DW1VWL.gif)

The weird part is that the three-dot editor dropdown menu _doesn't_ get overlayed. It looks like it was built with the same popover component as our button dropdown, so I would expect that it would behave the same way. I tried tinkering with z-indexes, but couldn't figure anything out 😕

**Comment by StevenDufresne** [comment]
I wasn't able to reproduce this using my FireFox(86) on macOs Catalina. 

Can you add more environment details?

**Comment by coreymckrill** [comment]
Oh wow. So, this only happens when I'm in Firefox's "Responsive design mode", which I was using yesterday to have a smaller screen size while recording a screencast. When I exit that mode, the scrollbar is underneath the button dropdown, as it should be.

I think we can safely close this one as an extreme edge case.
