### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by MarieComet** [WordPress/revisions-extended#110]
I'm unable to use the plugin.
I've downloaded .zip from GitHub repo, pasted "revisions-extended" subfolder to my wp-content/plugins folder, activated the plugin, but nothing change in editor (no button next to the update button).

Can you help me ?

Some informations about my install : 

`
### wp-core ###

version: 5.8.1
site_language: fr_FR
user_language: fr_FR
timezone: Europe/Paris
permalink: /%postname%/
https_status: false
multisite: false
user_registration: 1
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 10
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /app
wordpress_size: 89,75 Mo (94107531 bytes)
uploads_path: /app/wp-content/uploads
uploads_size: 16,27 Go (17468650779 bytes)
themes_path: /app/wp-content/themes
themes_size: 219,91 Mo (230595299 bytes)
plugins_path: /app/wp-content/plugins
plugins_size: 394,78 Mo (413959450 bytes)
database_size: 74,62 Mo (78243840 bytes)
total_size: 17,03 Go (18285556899 bytes)

### wp-active-theme ###

name: Test (test)
version: 1.0.0
author: bsa-web
author_website: http://bsa-web.fr
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, automatic-feed-links, title-tag, post-thumbnails, menus, html5, customize-selective-refresh-widgets, custom-logo, editor-color-palette, editor-font-sizes, editor-styles, editor-style, align-wide, responsive-embeds
theme_path: /app/wp-content/themes/test
auto_update: Désactivé

### wp-plugins-active (10) ###

CPT Actualité: version: 1.0, author: test, Mises à jour auto désactivées
CPT Biographie: version: 1.0, author: test, Mises à jour auto désactivées
CPT Communiqués de presse: version: 1.0, author: test, Mises à jour auto désactivées
CPT Langs: version: 1.0, author: test, Mises à jour auto désactivées
CPT Publications: version: 1.0, author: test, Mises à jour auto désactivées
CPT Resultats: version: 1.0, author: test, Mises à jour auto désactivées
CPT Évènement: version: 1.0, author: test, Mises à jour auto désactivées
Migrate PLL: version: 1.0, author: test, Mises à jour auto désactivées
Polylang: version: 3.1.1, author: WP SYNTEX, Mises à jour auto désactivées
Revisions Extended: version 0.1, author: WordPress.org, Mises à jour auto désactivées
Safe SVG: version: 1.9.9, author: Daryll Doyle, Mises à jour auto désactivées

### wp-server ###

server_architecture: Linux 5.4.0-88-generic x86_64
httpd_software: Apache/2.4.38 (Debian)
php_version: 7.4.16 64bit
php_sapi: apache2handler
max_input_variables: 10000
time_limit: 90
memory_limit: 1G
max_input_time: 900
upload_max_filesize: 100M
php_post_max_size: 100M
curl_version: 7.64.0 OpenSSL/1.1.1d
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 10.3.27-MariaDB
client_version: mysqlnd 7.4.16

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /app/wp-content
WP_PLUGIN_DIR: /app/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 1G
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
`

**Comment by coreymckrill** [comment]
Hi @MarieComet, the plugin won't work directly from this GitHub repo unless you run the script to compile the JavaScript files first (see the Development section of the readme file).

Alternatively, I just created a "release" version that includes a pre-built zip file here: https://github.com/WordPress/revisions-extended/releases/tag/v0.1.0-beta

If you download the `revisions-extended.0.1.0-beta.zip` file and install it in WordPress, it should work.

**Comment by LukaszJaro** [comment]
Tried the release version and still not working. Tried to build the files according to the instructions and not working either.

Can we re-open this? @coreymckrill

**Comment by coreymckrill** [comment]
@LukaszJaro can you provide more details? Are you seeing any error messages in WP or in the browser console?

**Comment by LukaszJaro** [comment]
Thanks for getting back Corey. No errors anywhere, not in wp or browser console. It's as if plugin doesn't even exist even though it's activated. I tried disabling all plugins and on another site but still nothing.

Here's the plugin folder structure:

![image](https://user-images.githubusercontent.com/10998875/138514082-6f892097-0f79-42c2-96e3-07adf676029f.png)

Also, I'm running WP 5.8.1

**Comment by coreymckrill** [comment]
@LukaszJaro with the plugin activated, if you go and edit an existing normal post, do you see the dropdown button next to the Update button?

![update-dropdown](https://user-images.githubusercontent.com/916023/138522861-234b5b77-150f-47d1-98d3-79f2e442a478.jpg)

Or any console errors on that screen?

**Comment by LukaszJaro** [comment]
No I don't, checked in code as well, nothing after button:

![image](https://user-images.githubusercontent.com/10998875/138536623-f248d278-0623-4ee5-9019-49a7b0b40749.png)

![image](https://user-images.githubusercontent.com/10998875/138536647-e4fabd7c-1847-4fd6-ad5d-958540e74ea6.png)

**Comment by LukaszJaro** [comment]
I downloaded the release again, it's working now! sorry about that!

Thank you for the help, this is am awesome plugin that I can finally test :)

**Comment by benlk** [comment]
Thank you for uploading the compiled .zip; I hope that you'll be able to release future updates to wp.org eventually!
