### ISSUE TITLE
UI: Move to Trash also triggers "savePost" when viewing a post/page.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/revisions-extended#12]
## Reproduce:
1. When viewing your published post, Select "Save as future update" checkbox
2. Click Move to Trash
3. Notice you get and error about creating a revision.

## Background
We replace Gutenberg's `savePost` function when the user selects "Save as future update". The problem is that the `trashPost` function deletes the record then calls `savePost`. Since the checkbox is toggled on, and we have replaced the `savePost` function, it then gets triggered.

We need to figure out how to determine the caller.

**Comment by coreymckrill** [comment]
Looks like this was fixed by #13.
