### ISSUE TITLE
Drop-Down Arrow Not Showing Next to "Update" Button

### ISSUE THREAD

**Issue by KimRoach7** [WordPress/revisions-extended#122]
I downloaded and activated the plugin, but there's no dropdown menu on the Update button in the upper right. There's no dropdown arrow showing. 

Someone else mentioned the same issue here in the comments section here - https://make.wordpress.org/core/2023/07/05/revisions/

Would love to use this plugin with our team!

When I activate the plugin, I can see a new section under posts that says "updates".

But there's currently no option that allows me to create or schedule a revision (when editing a published post).

**Comment by mahodder** [comment]
Same issue - it broke in the WP 6.3 release - it works fine in 6.2 and lower.

**Comment by StevenDufresne** [comment]
Hi 👋 .

I think I fixed this in 2e5a2116220b8ccfdf6013cd14911de8dc34dce5. Can you confirm that it works? 

If it's still an issue, please re-open. Thanks!

**Comment by mahodder** [comment]
This worked, thanks @StevenDufresne 👍
