### ISSUE TITLE
Edit revision: The WP button to "exit" the editor links to a revision list table page that we don't want

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/revisions-extended#14]
Reproduce:

* Create a new scheduled revision of a post
* Continue editing the new revision
* Click the WP logo button in the upper left corner to exit the block editor
* You'll go to `http://localhost:8888/wp-admin/edit.php?post_type=revision`

Needed changes:

- [x] Change the URL of the WP logo button to go to the custom "Scheduled Updates" page for the revision parent's post type
- [x] Remove access to that list table page, as we aren't using it

**Comment by StevenDufresne** [comment]
Completed when #38 was merged.

**Comment by coreymckrill** [comment]
#38 isn't solving the WP logo button URL issue for me. There seems to be a step missing, because the URL is not being modified.

**Comment by StevenDufresne** [comment]
Should be fixed with: https://github.com/coreymckrill/revisions-extended/commit/a2d86072af9dab6dcf333631b136d51ba25fa273.

Can you verify?

**Comment by coreymckrill** [comment]
Yep, fixed it! Thanks
