### ISSUE TITLE
Design feedback needed: The flow for creating a new scheduled update

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/revisions-extended#19]
![revision](https://user-images.githubusercontent.com/916023/106972114-12a17280-6705-11eb-99a9-ef8dd1f15903.gif)

As seen in the above animation, the current steps are:

1. Make changes to a post
2. Go to the document sidebar panel and check the box that says "Save as future update"
3. Change the publish date
4. Click "Create update" (which has replaced the normal "Update" button)
5. Choose to either continue editing the update, go back to the current live post content in the editor, or go to a list table showing all currently scheduled updates for that post type

Looking for feedback on:

* Does this flow make sense?
* How could it be improved?

**Comment by kellychoffman** [comment]
Looks good! I think the flow makes sense if someone shows you how to use it. A few suggestions to have it be more intuitive: 
- “Save as future update” is a bit out of context from the areas that have to do with saving + scheduling. I would move it above author so its just below the date. Is it possible to also automatically check this box if you were to first pick a date in the future? I think that would make it more intuitive and more clearly connect the two actions together. 
- Make the copy more consistent. Right now, we're using "create" and "save" interchangeably, for example.
- Success modal: This works, but was thinking it would also be good to utilize the post-publish sidebar panel and place that content in there. Not a deal breaker, tho.

**Comment by StevenDufresne** [comment]
> * “Save as future update” is a bit out of context from the areas that have to do with saving + scheduling. I would move it above author so its just below the date. 

This is difficult and added as a separate issue: #50 

> * Is it possible to also automatically check this box if you were to first pick a date in the future? I think that would make it more intuitive and more clearly connect the two actions together.
> * Make the copy more consistent. Right now, we're using "create" and "save" interchangeably, for example.

Addressed here: #51 

> * Success modal: This works, but was thinking it would also be good to utilize the post-publish sidebar panel and place that content in there. Not a deal breaker, tho.

I think we'll leave this for now because we need to stop user interactivity after they create the revision.

**Comment by coreymckrill** [comment]
#50 is the only part of this that's still unaddressed, but we can continue discussion there, so I'm going to close this.
