### ISSUE TITLE
Only title, content & excerpt are saved for revision. Consider saving other information.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/revisions-extended#23]
WordPress doesn't support other information for revisions and neither do we. 

I just want to log that we may want to support future updates to categories, tags, etc...

**Comment by coreymckrill** [comment]
I think this issue would be better tackled in Core, and then this plugin would benefit from that without too much additional work.

**Comment by StevenDufresne** [comment]
Agree with Corey.
