### ISSUE TITLE
Need a way to retrieve post parent type. 

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/revisions-extended#27]
There are a couple of use cases that we are working on that require knowledge of the parent's post type when editing a revision:

1. **Language**: We make reference to the original `post/page` in a few spots.
2. Redirecting to the correct list (https://github.com/coreymckrill/revisions-extended/pull/24#issuecomment-774804386).

I have looked into trying to request the post/page using the WP API but it seems like you need to know the post type in order to make the request seeing that the WP endpoints require it `../pages`, `../posts`. 

### Options:
1. Create our own endpoint to retrieve the parent post type.
2. Assign the parent post type to the revision record.
3. ... ?

**Comment by coreymckrill** [comment]
Another possible option might be to do [what we did with author data](https://github.com/coreymckrill/revisions-extended/commit/bcb44045e19f24406823faf8238cc6f48016dda2) and make the parent embeddable in revision responses. So, in the `get_items` and `get_item` endpoints. I'll spin up and PR and see what that looks like.
