### ISSUE TITLE
When editing a revision, the "Update" button reads "Schedule".

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/revisions-extended#53]
The button reads `Schedule` because Gutenberg sees the revision as a future post. Programmatically changing the innerText using javascript creates Gutenberg errors.

Hopefully, we can leverage, which is set to launch with WP 5.7.
https://github.com/WordPress/gutenberg/issues/14833#issuecomment-768999141

**Comment by coreymckrill** [comment]
That change is already in the released 9.9 version of Gutenberg, I think. The Gutenberg plugin is installed on wp.org, so I think we should go ahead and use this change now, rather than waiting for Core.
