### ISSUE TITLE
Error when starting up a local environment

### ISSUE THREAD

**Issue by ryelle** [WordPress/revisions-extended#64]
I ran into an error when trying to install the local environment. This is with #63, so it's possible there's a version difference in wp-env, if you're running it globally?

```
> wp-env "start"

✖ Error while running docker-compose command.
Step 1/6 : FROM wordpress:php5.6
 ---> ed4f6f58673b
Step 2/6 : RUN apt -qy install $PHPIZE_DEPS 	&& pecl install xdebug 	&& docker-php-ext-enable xdebug
 ---> Running in 778a2b61fa9e

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
make is already the newest version (4.1-9.1).
re2c is already the newest version (0.16-2).
autoconf is already the newest version (2.69-10).
gcc is already the newest version (4:6.3.0-4).
file is already the newest version (1:5.30-1+deb9u2).
pkg-config is already the newest version (0.29-4+b1).
dpkg-dev is already the newest version (1.18.25).
g++ is already the newest version (4:6.3.0-4).
libc6-dev is already the newest version (2.24-11+deb9u3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
pecl/xdebug requires PHP (version >= 7.2.0, version <= 8.0.99), installed version is 5.6.39
No valid packages found
install failed
Building wordpress
Service 'wordpress' failed to build : The command '/bin/sh -c apt -qy install $PHPIZE_DEPS 	&& pecl install xdebug 	&& docker-php-ext-enable xdebug' returned a non-zero code: 1
```

It seemed related to php 5.6, so I removed `"phpVersion": "5.6",` from the `.wp-env.json` and that fixed it, but I'm not sure if you wanted 5.6 intentionally.

**Comment by coreymckrill** [comment]
Looks like it's related to this: https://github.com/WordPress/gutenberg/issues/27783

Using PHP 5.6 is intentional, trying to develop to WP's minimum requirements.

I'm not sure why I haven't run into this before, it could be that I wasn't _actually_ running PHP 5.6 like I thought, or maybe the xdebug feature got added later?

**Comment by coreymckrill** [comment]
A workaround until this is fixed upstream is to add a **.wp-env.override.json** file (which is gitignored) with this in it:

```
{
	"phpVersion": "7.2"
}
```

**Comment by ryelle** [comment]
Yeah, I bet your containers were built before this was added. The workaround suggestion works for me, so I'll close this issue.
