### ISSUE TITLE
Note: Future date - starts tomorrow?

### ISSUE THREAD

**Issue by bph** [WordPress/revisions-extended#65]
This was my first attempt to work with the new feature! So happy this is almost here!!! 

When I tried to save via the **Create Update** button, to see if it changes in 30 minutes.  I got this nice warning. "We currently only support updates with future publish dates. Please select a date in the future?" 

I tried it again, in two hours, same message. It didn't tell me that future, doesn't mean "in two hours". But it didn't tell me how to fix this. Once I actually changed the date to tomorrow, it would save. 

I don't have a suggestion for a better copy of the message — yet. Sorry. Is there a technical reason why the future is measured in days rather than in hours? 

Use cases for a today publishing date rather than tomorrow? 
- Birgit testing this fabulous new feature and doesn't want to wait until tomorrow. 
- An event announcement post is transformed to a post to with video link, slide deck and resources after the live event is over, replacing all the future language to past tense. 
- WordCamp's schedule page with the latest information to go live.

**Comment by StevenDufresne** [comment]
> This was my first attempt to work with the new feature! So happy this is almost here!!!
> 
> When I tried to save via the **Create Update** button, to see if it changes in 30 minutes. I got this nice warning. "We currently only support updates with future publish dates. Please select a date in the future?"
> 
> I tried it again, in two hours, same message. It didn't tell me that future, doesn't mean "in two hours". But it didn't tell me how to fix this. Once I actually changed the date to tomorrow, it would save.
> 
> I don't have a suggestion for a better copy of the message — yet. Sorry. Is there a technical reason why the future is measured in days rather than in hours?
> 
> Use cases for a today publishing date rather than tomorrow?
> 
> * Birgit testing this fabulous new feature and doesn't want to wait until tomorrow.
> * An event announcement post is transformed to a post to with video link, slide deck and resources after the live event is over, replacing all the future language to past tense.
> * WordCamp's schedule page with the latest information to go live.

This should be considered a bug. I'll look into it.

**Comment by StevenDufresne** [comment]
I can only reproduce in this scenario:

1. Create a new page
2. Publish New page
3. Change Date to 1 minute later (do it quickly after post :))
4. Try to create a new revision
5. Verify the Warning message.

_It happens when there is less than a 1-minute difference from the published date._

**So, can I get more details of the issue you are seeing?** 

If possible, and you are comfortable, can you changing the date, copy the following to your console:

```
console.log('newDate', wp.data.select('core/editor').getEditedPostAttribute('date'))
console.log('oldDate', wp.data.select('core/editor').getCurrentPostAttribute('date'))
```

and share it here?

**Comment by coreymckrill** [comment]
@bph my first thought is that the test site is set to a different timezone than you are in, so even though you set it for two hours ahead of your current time, it was still in the past for the site. Is that a possible cause here?

**Comment by bph** [comment]
I hadn't considered a timezone problem. With the site being at UTC +0 and me being in UTC -5 -  You are right on, @coreymckrill - sorry about that. 

I also saw the changes published with no trouble.  However, when I went back in again it still has the original publication date. Is that wanted behavior? I can open up a new issue. Closing this for now.

**Comment by coreymckrill** [comment]
> when I went back in again it still has the original publication date. Is that wanted behavior?

My assumption is that we would want a post to retain its original publication date. Just as if you edit a post and save those changes immediately (rather than scheduling them for later), the publication date stays the same. The _Last modified_ date should change though.
