### ISSUE TITLE
Add "current" to edit page. 

### ISSUE THREAD

**Issue by bph** [WordPress/revisions-extended#66]
I am happy that I have a locator on top that tells me I am working on a scheduled update. 
<img width="547" alt="Screen Shot 2021-02-20 at 9 14 00 AM" src="https://user-images.githubusercontent.com/39980/108598635-b709f280-735c-11eb-8ef1-663ea7884cd5.png">

If the link **Edit Page** could be changed to 'currently published page' it makes clear to me that where I land when I follow it. 
Not sure about the copy, though. 

- 'Edit current page'
- 'Edit published page'
- 'Edit currently published page' 

I fight the yearning for brevity with the need for  precision...

**Comment by coreymckrill** [comment]
Yeah, I've been struggling to find the right wording for a lot of things in this plugin. A couple more ideas:

* Edit live page
* Edit original page
