### ISSUE TITLE
Timezone confusion leads to error and redirect

### ISSUE THREAD

**Issue by iandunn** [WordPress/revisions-extended#72]
1. Edit a scheduled revision
2. Click on the publish date. The datepicker shows the time in UTC, which is confusing for most people (related to #70)?
3. Change the date to today. The `We currently only support updates with future publish dates. Please select a date in the future.` warning is not shown.
4. Pick a time that is in the future _in your time zone_, but is actually in the past _in UTC_.
5. Click Publish. You'll get a series of `alert` boxes asking if you want to leave the page (related #57). Then, you'll get a `Updating failed. Invalid parameter(s): status` box. Then you'll be redirected to the original page, rather than staying on the scheduled revision.

That kind of makes sense in hindsight, but I imagine it'll be confusing to people. Preventing people from picking dates in the past might be a good fix.

**Comment by coreymckrill** [comment]
Related: #56

**Comment by iandunn** [comment]
Er, yeah, just saw that. This is probably a dupe.

**Comment by StevenDufresne** [comment]
Just making a note that the date in UTC is inherited from the WordPress timezone setting.

**Comment by iandunn** [comment]
Ah, thanks for pointing that out. I opened https://github.com/WordPress/gutenberg/issues/29306 to address that.
