### ISSUE TITLE
Full Site Editing: Turn off plugin when user is editing template.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/revisions-extended#78]
Full site editing uses a custom post type for editing template parts. Our controls are being registered on those pages. 

If that implementation is how it will work going forward we should check for the custom post type and not enqueue our assets.

Post Type: `wp_template`

Code: https://github.com/coreymckrill/revisions-extended/blob/46b6a42590e302445fb90ae83a080a3d5d7bb572/revisions-extended/includes/admin.php#L82

**Comment by coreymckrill** [comment]
Updates are set up to work with any post type that supports revisions, so the `wp_template` post type must do that. For now, I think we can just add an exception for that specific post type.
