### ISSUE TITLE
Excerpt field in update editor should only be visible if the parent post type supports excerpts

### ISSUE THREAD

**Issue by DaisyOlsen** [WordPress/revisions-extended#89]
I noticed on both a post update and a CPT update there is an excerpt screen.Adding content to that field causes an error on save. This could be a post type supports change, but I didn't look at any code :-)

**Comment by coreymckrill** [comment]
We definitely shouldn't show the excerpt field on updates for post types that don't support excerpts. I haven't been able to reproduce the error though. When I tried it for Handbook pages on the test site, it let me save an excerpt without issue. @DaisyOlsen could you provide a step-by-step of how to get the error?

**Comment by DaisyOlsen** [comment]
I'll try to reproduce with a screencast tomorrow.

**Comment by DaisyOlsen** [comment]
I can only think that there was user error involved here. I wasn't able to reproduce it again either. Disregard.

**Comment by StevenDufresne** [comment]
This should be set on the revision post type itself. The UI should update appropriately.

![](https://d.pr/i/xLnOgT.png)
