### ISSUE TITLE
Clicking the dropdown arrow on the Update button should toggle the dropdown state

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/revisions-extended#97]
Right now clicking the button always opens the dropdown, even if it's already open. In that case, it should close the dropdown instead.

**Comment by StevenDufresne** [comment]
I'm don't think I see the same thing you are getting, but the arrow down button does get a focus state until the user clicks away.

![](https://d.pr/i/rHOUqd.gif)

**Comment by coreymckrill** [comment]
Oh interesting. Maybe it's a browser-specific issue. Here's what I'm seeing in Firefox:

![](https://d.pr/i/FHWaQ3.gif)

**Comment by StevenDufresne** [comment]
This issue exists within the Gutenberg component.

Issue filed: WordPress/gutenberg#29746

**Comment by coreymckrill** [comment]
Oops, I didn't mean to close this yesterday, but since it's an upstream issue, I guess I'll leave it closed now.
